### ISSUE TITLE
EE4 Integration?

### ISSUE THREAD

**Issue by KinnaT** [eventespresso/espresso-breakout#1]
This is the exact thing I need for a site I'm building. This and the ability to export approved and checked-in registrations for expired events from the front end are the last two pieces of the puzzle. 
Is it possible that this would work in EE4?  If not, what do you suppose is the level of effort to get it to work? I'm willing to take that on, since this very specific use case is the exact use case I now have. The functionality would suit my needs perfectly, just possibly adding in pre-population for the registration ID against registrant email and logged-in user email.  I'm already running the EE4 user integration and multiple events add-ons, which should help for multiple sessions of a single breakout event.
Will these breakout events also show on the events list/calendar? If so, do you know of a way to hide them?
Thank you for making this!

**Comment by nerrad** [comment]
The espresso-breakout add-on is only compatible with EE3 (I just updated the README.md to make that more clear).

I don't think this is something that we will invest any more development time in to make available for EE4 because EE4 already provides similar functionality.  If you have a support license with Event Espresso, you can post in the forums there and one of the support staff will get back to you on how you can achieve similar functionality with EE4.
